<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10</LangVersion>
    <RootNamespace>DebugBridge.Contract</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\samples\**\*.json" CopyToOutputDirectory="PreserveNewest" LinkBase="samples" />
  </ItemGroup>
</Project>

